# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(676, 536)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_refreshPorts = QtWidgets.QPushButton(Form)
        self.pb_refreshPorts.setObjectName("pb_refreshPorts")
        self.gridLayout.addWidget(self.pb_refreshPorts, 2, 0, 1, 1)
        self.pb_closePort = QtWidgets.QPushButton(Form)
        self.pb_closePort.setObjectName("pb_closePort")
        self.gridLayout.addWidget(self.pb_closePort, 2, 3, 1, 1)
        self.pb_openPort = QtWidgets.QPushButton(Form)
        self.pb_openPort.setObjectName("pb_openPort")
        self.gridLayout.addWidget(self.pb_openPort, 2, 2, 1, 1)
        self.cb_ports = QtWidgets.QComboBox(Form)
        self.cb_ports.setObjectName("cb_ports")
        self.gridLayout.addWidget(self.cb_ports, 2, 1, 1, 1)
        self.lbl_status = QtWidgets.QLabel(Form)
        self.lbl_status.setText("")
        self.lbl_status.setObjectName("lbl_status")
        self.gridLayout.addWidget(self.lbl_status, 2, 4, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.sb_y = QtWidgets.QSpinBox(self.tab_2)
        self.sb_y.setMaximum(300)
        self.sb_y.setProperty("value", 150)
        self.sb_y.setObjectName("sb_y")
        self.gridLayout_4.addWidget(self.sb_y, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.sb_x = QtWidgets.QSpinBox(self.tab_2)
        self.sb_x.setMinimum(0)
        self.sb_x.setMaximum(300)
        self.sb_x.setProperty("value", 150)
        self.sb_x.setObjectName("sb_x")
        self.gridLayout_4.addWidget(self.sb_x, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.sb_step = QtWidgets.QSpinBox(self.tab_2)
        self.sb_step.setProperty("value", 8)
        self.sb_step.setObjectName("sb_step")
        self.gridLayout_4.addWidget(self.sb_step, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.sb_axis_z = QtWidgets.QSpinBox(self.tab_2)
        self.sb_axis_z.setProperty("value", 20)
        self.sb_axis_z.setObjectName("sb_axis_z")
        self.gridLayout_4.addWidget(self.sb_axis_z, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 5, 0, 1, 1)
        self.sb_speed = QtWidgets.QSpinBox(self.tab_2)
        self.sb_speed.setMaximum(6)
        self.sb_speed.setProperty("value", 4)
        self.sb_speed.setObjectName("sb_speed")
        self.gridLayout_4.addWidget(self.sb_speed, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 4, 0, 1, 1)
        self.sb_passages = QtWidgets.QSpinBox(self.tab_2)
        self.sb_passages.setMaximum(20)
        self.sb_passages.setProperty("value", 2)
        self.sb_passages.setObjectName("sb_passages")
        self.gridLayout_4.addWidget(self.sb_passages, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pb_generateGCode = QtWidgets.QPushButton(self.tab_3)
        self.pb_generateGCode.setObjectName("pb_generateGCode")
        self.gridLayout_2.addWidget(self.pb_generateGCode, 0, 0, 1, 1)
        self.pte_displayGCode = QtWidgets.QPlainTextEdit(self.tab_3)
        self.pte_displayGCode.setObjectName("pte_displayGCode")
        self.gridLayout_2.addWidget(self.pte_displayGCode, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pb_start = QtWidgets.QPushButton(self.tab_4)
        self.pb_start.setObjectName("pb_start")
        self.gridLayout_3.addWidget(self.pb_start, 0, 1, 1, 1)
        self.pb_clear = QtWidgets.QPushButton(self.tab_4)
        self.pb_clear.setObjectName("pb_clear")
        self.gridLayout_3.addWidget(self.pb_clear, 0, 0, 1, 1)
        self.pte_generateGCode = QtWidgets.QPlainTextEdit(self.tab_4)
        self.pte_generateGCode.setObjectName("pte_generateGCode")
        self.gridLayout_3.addWidget(self.pte_generateGCode, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 5)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pb_refreshPorts.setText(_translate("Form", "Mettre à jour les ports"))
        self.pb_closePort.setText(_translate("Form", "Close"))
        self.pb_openPort.setText(_translate("Form", "Connect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Presentation"))
        self.label.setText(_translate("Form", "Longueur (mm)"))
        self.label_2.setText(_translate("Form", "Largeur du plateau (mm)"))
        self.label_3.setText(_translate("Form", "Déplacement du porte-aiguille (mm)"))
        self.label_4.setText(_translate("Form", "Déplacement de l\'axe Z (mm)"))
        self.label_5.setText(_translate("Form", "Vitesse"))
        self.label_6.setText(_translate("Form", "Nombre d\'actions de l\'outil-aiguilles "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Paramètres"))
        self.pb_generateGCode.setText(_translate("Form", "Générer le GCode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Génération du GCode"))
        self.pb_start.setText(_translate("Form", "Lancer"))
        self.pb_clear.setText(_translate("Form", "effacer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Lancement du cycle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
