# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FeutrageGUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(992, 740)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.cb_ports = QtWidgets.QComboBox(self.centralwidget)
        self.cb_ports.setObjectName("cb_ports")
        self.gridLayout.addWidget(self.cb_ports, 2, 1, 1, 1)
        self.pb_closePort = QtWidgets.QPushButton(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pb_closePort.setPalette(palette)
        self.pb_closePort.setObjectName("pb_closePort")
        self.gridLayout.addWidget(self.pb_closePort, 2, 3, 1, 1)
        self.pb_openPort = QtWidgets.QPushButton(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pb_openPort.setPalette(palette)
        self.pb_openPort.setObjectName("pb_openPort")
        self.gridLayout.addWidget(self.pb_openPort, 2, 2, 1, 1)
        self.pb_resfreshPorts = QtWidgets.QPushButton(self.centralwidget)
        self.pb_resfreshPorts.setObjectName("pb_resfreshPorts")
        self.gridLayout.addWidget(self.pb_resfreshPorts, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 4, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.tab_1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 9, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 5, 0, 1, 1)
        self.sb_x = QtWidgets.QSpinBox(self.tab_4)
        self.sb_x.setMaximum(600)
        self.sb_x.setProperty("value", 150)
        self.sb_x.setObjectName("sb_x")
        self.gridLayout_3.addWidget(self.sb_x, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 6, 0, 1, 1)
        self.sb_axis_z = QtWidgets.QSpinBox(self.tab_4)
        self.sb_axis_z.setMaximum(600)
        self.sb_axis_z.setProperty("value", 20)
        self.sb_axis_z.setObjectName("sb_axis_z")
        self.gridLayout_3.addWidget(self.sb_axis_z, 6, 1, 1, 1)
        self.lbl_realTime = QtWidgets.QLabel(self.tab_4)
        self.lbl_realTime.setText("")
        self.lbl_realTime.setObjectName("lbl_realTime")
        self.gridLayout_3.addWidget(self.lbl_realTime, 1, 1, 1, 1)
        self.sb_step = QtWidgets.QSpinBox(self.tab_4)
        self.sb_step.setProperty("value", 8)
        self.sb_step.setObjectName("sb_step")
        self.gridLayout_3.addWidget(self.sb_step, 5, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab_4)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 8, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 4, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab_4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.lbl_elapsed_time = QtWidgets.QLabel(self.tab_4)
        self.lbl_elapsed_time.setObjectName("lbl_elapsed_time")
        self.gridLayout_3.addWidget(self.lbl_elapsed_time, 3, 0, 1, 1)
        self.sb_y = QtWidgets.QSpinBox(self.tab_4)
        self.sb_y.setMaximum(600)
        self.sb_y.setProperty("value", 150)
        self.sb_y.setObjectName("sb_y")
        self.gridLayout_3.addWidget(self.sb_y, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 7, 0, 1, 1)
        self.sb_speed = QtWidgets.QSpinBox(self.tab_4)
        self.sb_speed.setMaximum(8)
        self.sb_speed.setProperty("value", 4)
        self.sb_speed.setObjectName("sb_speed")
        self.gridLayout_3.addWidget(self.sb_speed, 7, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pte_displayGCode = QtWidgets.QPlainTextEdit(self.tab_2)
        self.pte_displayGCode.setObjectName("pte_displayGCode")
        self.gridLayout_4.addWidget(self.pte_displayGCode, 1, 0, 1, 1)
        self.pb_generateGCode = QtWidgets.QPushButton(self.tab_2)
        self.pb_generateGCode.setObjectName("pb_generateGCode")
        self.gridLayout_4.addWidget(self.pb_generateGCode, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pb_start = QtWidgets.QPushButton(self.tab)
        self.pb_start.setObjectName("pb_start")
        self.gridLayout_8.addWidget(self.pb_start, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 992, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Feutrage de laine"))
        self.pb_closePort.setText(_translate("MainWindow", "Close"))
        self.pb_openPort.setText(_translate("MainWindow", "Connect"))
        self.pb_resfreshPorts.setText(_translate("MainWindow", "Mettre à jour les ports"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:700;\">Feutrage de laine</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>Ce logiciel a pour objectif de lancer un cycle de feutrage.</p><p><br/></p><p> Avant de lancer un cycle, il faut bien vérifier que les paramètres saisis sont les bons.</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Présentation"))
        self.label_3.setText(_translate("MainWindow", "Déplacement du porte-aiguilles (mm)"))
        self.label_4.setText(_translate("MainWindow", "Déplacement de l\'axe Z (mm)"))
        self.label.setText(_translate("MainWindow", "Largeur du plateau (mm)"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">Paramètres</span></p></body></html>"))
        self.lbl_elapsed_time.setText(_translate("MainWindow", "Longueur du plateau (mm)"))
        self.label_7.setText(_translate("MainWindow", "Vitesse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Paramètres"))
        self.pb_generateGCode.setText(_translate("MainWindow", "Générer le GCode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Génération du GCode"))
        self.pb_start.setText(_translate("MainWindow", "Lancer le cycle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Lancement du cycle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
