# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FeutrageGUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 740)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_status = QtWidgets.QLabel(self.centralwidget)
        self.lbl_status.setObjectName("lbl_status")
        self.gridLayout.addWidget(self.lbl_status, 2, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 5, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 712, 812))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("img/cycle.png"))
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pte_displayGCode = QtWidgets.QPlainTextEdit(self.tab_2)
        self.pte_displayGCode.setReadOnly(True)
        self.pte_displayGCode.setPlaceholderText("")
        self.pte_displayGCode.setObjectName("pte_displayGCode")
        self.gridLayout_4.addWidget(self.pte_displayGCode, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 0, 0, 1, 1)
        self.pte_gcodeReturn = QtWidgets.QPlainTextEdit(self.tab)
        self.pte_gcodeReturn.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.pte_gcodeReturn.setObjectName("pte_gcodeReturn")
        self.gridLayout_8.addWidget(self.pte_gcodeReturn, 1, 0, 1, 3)
        self.pb_clear = QtWidgets.QPushButton(self.tab)
        self.pb_clear.setObjectName("pb_clear")
        self.gridLayout_8.addWidget(self.pb_clear, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 8)
        self.pb_progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.pb_progressBar.setProperty("value", 0)
        self.pb_progressBar.setObjectName("pb_progressBar")
        self.gridLayout.addWidget(self.pb_progressBar, 2, 7, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dw_settings = QtWidgets.QDockWidget(MainWindow)
        self.dw_settings.setObjectName("dw_settings")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_13 = QtWidgets.QLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 0, 0, 1, 2)
        self.cb_ports = QtWidgets.QComboBox(self.dockWidgetContents)
        self.cb_ports.setObjectName("cb_ports")
        self.gridLayout_6.addWidget(self.cb_ports, 2, 1, 1, 1)
        self.sb_speed = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.sb_speed.setMaximum(8)
        self.sb_speed.setProperty("value", 4)
        self.sb_speed.setObjectName("sb_speed")
        self.gridLayout_6.addWidget(self.sb_speed, 10, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 8, 0, 1, 1)
        self.sb_x = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.sb_x.setMaximum(600)
        self.sb_x.setProperty("value", 30)
        self.sb_x.setObjectName("sb_x")
        self.gridLayout_6.addWidget(self.sb_x, 6, 1, 1, 1)
        self.pb_closePort = QtWidgets.QPushButton(self.dockWidgetContents)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 41, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pb_closePort.setPalette(palette)
        self.pb_closePort.setObjectName("pb_closePort")
        self.gridLayout_6.addWidget(self.pb_closePort, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 10, 0, 1, 1)
        self.pb_generateGCode = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pb_generateGCode.setEnabled(False)
        self.pb_generateGCode.setObjectName("pb_generateGCode")
        self.gridLayout_6.addWidget(self.pb_generateGCode, 11, 0, 1, 2)
        self.pb_openPort = QtWidgets.QPushButton(self.dockWidgetContents)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 226, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pb_openPort.setPalette(palette)
        self.pb_openPort.setObjectName("pb_openPort")
        self.gridLayout_6.addWidget(self.pb_openPort, 3, 0, 1, 1)
        self.sb_passages = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.sb_passages.setProperty("value", 2)
        self.sb_passages.setObjectName("sb_passages")
        self.gridLayout_6.addWidget(self.sb_passages, 9, 1, 1, 1)
        self.sb_y = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.sb_y.setMaximum(600)
        self.sb_y.setProperty("value", 30)
        self.sb_y.setObjectName("sb_y")
        self.gridLayout_6.addWidget(self.sb_y, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 6, 0, 1, 1)
        self.sb_axis_z = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.sb_axis_z.setMinimum(2)
        self.sb_axis_z.setMaximum(10)
        self.sb_axis_z.setProperty("value", 2)
        self.sb_axis_z.setObjectName("sb_axis_z")
        self.gridLayout_6.addWidget(self.sb_axis_z, 8, 1, 1, 1)
        self.pb_resfreshPorts = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pb_resfreshPorts.setObjectName("pb_resfreshPorts")
        self.gridLayout_6.addWidget(self.pb_resfreshPorts, 1, 0, 1, 2)
        self.sb_step = QtWidgets.QSpinBox(self.dockWidgetContents)
        self.sb_step.setProperty("value", 8)
        self.sb_step.setObjectName("sb_step")
        self.gridLayout_6.addWidget(self.sb_step, 7, 1, 1, 1)
        self.pb_start = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pb_start.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(78, 154, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.pb_start.setPalette(palette)
        self.pb_start.setObjectName("pb_start")
        self.gridLayout_6.addWidget(self.pb_start, 12, 0, 1, 2)
        self.lbl_elapsed_time = QtWidgets.QLabel(self.dockWidgetContents)
        self.lbl_elapsed_time.setObjectName("lbl_elapsed_time")
        self.gridLayout_6.addWidget(self.lbl_elapsed_time, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 4, 0, 1, 2)
        self.pb_stop = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pb_stop.setObjectName("pb_stop")
        self.gridLayout_6.addWidget(self.pb_stop, 13, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 9, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 14, 0, 1, 1)
        self.dw_settings.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dw_settings)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Feutrage de laine"))
        self.lbl_status.setText(_translate("MainWindow", "Non connecté"))
        self.label_8.setText(_translate("MainWindow", "Cycle : "))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:700;\">Feutrage de laine</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>Ce logiciel permet de lancer des cycles de feutrage.</p><p>Avant de lancer un cycle, il faut bien vérifier que les paramètres sont corrects.</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">Déplacements</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Présentation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Génération du GCode"))
        self.label_9.setText(_translate("MainWindow", "Retour GCode"))
        self.pb_clear.setText(_translate("MainWindow", "Effacer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Lancement du cycle"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">Connexion</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "Port connecté"))
        self.label_3.setText(_translate("MainWindow", "Déplacement du porte-aiguilles (mm)"))
        self.label_4.setText(_translate("MainWindow", "Déplacement de l\'axe Z (mm)"))
        self.pb_closePort.setText(_translate("MainWindow", "Fermer"))
        self.label_7.setText(_translate("MainWindow", "Vitesse"))
        self.pb_generateGCode.setText(_translate("MainWindow", "Générer le GCode"))
        self.pb_openPort.setText(_translate("MainWindow", "Se connecter"))
        self.label.setText(_translate("MainWindow", "Largeur du plateau (mm)"))
        self.pb_resfreshPorts.setText(_translate("MainWindow", "Mettre à jour les ports"))
        self.pb_start.setText(_translate("MainWindow", "Lancer le cycle"))
        self.lbl_elapsed_time.setText(_translate("MainWindow", "Longueur du plateau (mm)"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700;\">Paramètres</span></p></body></html>"))
        self.pb_stop.setText(_translate("MainWindow", "Arreter"))
        self.label_12.setText(_translate("MainWindow", "Nombre de passage Z"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
